### PR TITLE
chore: add contributors section

### PR DESCRIPTION
**Pull request by JuanVqz**
image

### CODE REVIEW

**Comment by JuanVqz** [comment]
@rajasegar, I tried to add your info if something is wrong sorry and please change it.

**Comment by JuanVqz** [comment]
BTW, I want to change the `mocha` library to the `jest` library, I haven't found good documentation and standards on the `mocha` library, what do you think about it? can I change it?
to you what is more important resolve the issues that we already have or work on improving the code and test?

I saw a discussions section in another GitHub repos, would you add it? I think it's a good please to resolve questions, plan features, etc.

good night! :zzz:

**Comment by rajasegar** [comment]
@JuanVqz Added the Discussions panel to the repo, now we can discuss about anything there
https://github.com/rajasegar/alacritty-themes/discussions

**Pull request merged**
