### PR TITLE
refactor: rename theme files

### PR DESCRIPTION
**Pull request by JuanVqz**
@rajasegar Hello!

- [x] replace uppercases with lowercases "Something.yml" => "something.yml"
- [x] replace slashes with an underscore "Something - here - light.yml" => "something_here_light.yml"

I did this way thinking in the "parameterize" the theme's name.

now, I have some questions.

1. what about if we may want to search by only light themes?

  > that is the reason I'm not changing the ".light.yml" and ".dark.yml" yet

2. what do you think to add ".light.yml" to all files which don't have ".dark.yml"?

> but I realize another special case let's say `ayu` theme, it has
  `light`, `dark` and `mirage` colors, where we will categorize `mirage`?

3. What about changing "atelierdune.light.yml" and use
   "atelierdune_light.yml"?

> why we should use the ".light" like a file format.

I got a fun time doing this with a node.js script (I didn't pushed because we don't needed it anymore)

### CODE REVIEW

**Comment by JuanVqz** [comment]
Once we have the standard theme's name we can add it to the name on each file content.

**Comment by rajasegar** [comment]
My thoughs:
- We are using the filenames for display the theme names in the prompt list, if we replace all names with lower case it might look weird.
- What kind of advantages we are bringing in by changing the filename convention to underscores?
- All the themes need not to have a light and dark version by default, so we can not depend on that.
- And the most important one, this program is focused more on the ability to choose and apply the themes which have been already built by someone, and the main goal is not to standardize the theme names or formats but only to use them.

**Comment by rajasegar** [comment]
@JuanVqz I really appreciate the work you are doing here by bringing in a lot of value to the codebase. We also need to have our vision and goals focused to the core capabilities of the program in alignment with the principle `Do one thing and do it well`

**Comment by JuanVqz** [comment]
You are right! You can close this PR.

**Comment by JuanVqz** [comment]
I understand that we should focus on do one thing and do it well but sincerely I’d like to see an order in the theme’s names I feel like it is a mess. Some of themes with slashes, another one with spaces, etc.

I suggest all in lower case but we can use `Ayu Mirage` (with first letter per word on uppercase), or `Aye-Dark` whenever you like but have a standard way to name it.

We can list the theme's name as uppercase changing it before showing the list.

**Comment by rajasegar** [comment]
I don't see any slashes in names, but yeah spaces and inconsistencies are there,  I like this one `Aye-Dark`

**Comment by JuanVqz** [comment]
@rajasegar we have some files with  this format `Baskerville-Ivory-Dark.yml` and others with this other format `Atelierseaside.dark.yml`

do we need to define a convention here? we may use `Dark` in its name like the first one, which one do you like?

if it's ok like right now it is, you can review it, thank you.

**Pull request closed without merging**
