### PR TITLE
[Add Palenight Theme]

### LINKED ISSUE #62: Permission to add a theme
I would like to have permission to add a theme.

I already cloned and added the palenight.yml locally.
If thats ok of course.

If that is not possible, could you add a Palenight theme?

### PR DESCRIPTION
**Pull request by tiagaoalb**
I miss this theme in the repo, so I added it myself. Hope you enjoy.
palenight_screenshot

Closes #62

### CODE REVIEW

**Comment by JuanVqz** [comment]
It looks good, could you capitalize the first letter, please? Palenight.yml

It is like the color schemes I used to use. 👏

**Comment by tiagaoalb** [comment]
> It looks good, could you capitalize the first letter file, please? Palenight.yml
> 
> It is like the color schemes I used to use. clap
> 
> What promt's theme are you using?

Oh-my-zsh with spaceship.

**Comment by JuanVqz** [comment]
> > It looks good, could you capitalize the first letter file, please? Palenight.yml
> 
> > 
> 
> > It is like the color schemes I used to use. clap
> 
> > 
> 
> > What promt's theme are you using?
> 
> 
> 
> Oh-my-zsh with spaceship.

Thank you, I'll check it out, I already use oh my zsh.

And thank you for adding a new theme, we are always welcoming improvements if you want to contributing. Have a great day!

**Pull request merged**
