### PR TITLE
Add support for TOML

### PR DESCRIPTION
**Pull request by danilo-alm**
**Addressing issues #260 and #261**

Some important considerations you might want to address:
- Alacritty supports TOML file inclusion, so I'm including the file theme instead of copying its contents to the alacritty config;
- Unused keys now trigger a warning prompting for user action, thus I left every theme's "name" and "author" keys commented out, since leaving them as keys would trigger the annoying warning;
- The previous point implied that we cannot simply read the theme's "name" key to get its name, so I used their filenames;
- A few themes' specific keys were not recognized by Alacritty; I commented them out (commit be3902c);
- Tests were already broken, so I didn't bother fixing them for TOML. I tested the options available in --help manually and everything seemed okay.

### CODE REVIEW

**Comment by danilo-alm** [comment]
The themes were converted to TOML using the script (yml_to_toml.py, 9e1b7c3).

**Comment by danilo-alm** [comment]
May be a problem to some people: I just noticed this approach **wipes all comments**. There's a discussion about comment-preserving parsers [here](https://github.com/toml-lang/toml/issues/284) and it seems that there aren't many, especially in javascript. It'd be a good to put a warning in the README.

**Comment by rajasegar** [comment]
@danilo-alm Thanks for pitching in for the TOML support
What do you mean by tests are already broken?
Do you think you can fix it, that would be greatly appreciated

**Comment by danilo-alm** [comment]
I ran the tests and I think 5 failed. Then I went checked out to the current master commit and 4 were already failing if I remember correctly. Idk if I can fix them, I'll take a look later and let you know

**Comment by rajasegar** [comment]
@danilo-alm Thanks a lot for the PR, the changes are merged and a new release is cut

**Pull request merged**
