### PR TITLE
Add Moonlight II VSCode theme

### PR DESCRIPTION
**Pull request by otavionetoca**
Cool theme I bumped into, while trying to make my setup look a little bit more enjoyable.

taken from: https://github.com/eendroroy/alacritty-theme/blob/master/themes/moonlight_ii_vscode.yaml
source: https://github.com/atomiks/moonlight-vscode-theme

image

(don't tell anyone, but I use Arch btw and yes, running in a VM cause I'm too lazy to dual boot as well as too accommodated to leave windows)

### CODE REVIEW

**Comment by JuanVqz** [comment]
@otavionetoca thanks for adding a new theme to the collection. :rocket:

**Comment by JuanVqz** [comment]
@otavionetoca I'm using it, I love it :1st_place_medal:

**Comment by otavionetoca** [comment]
It makes me glad to read that, for real!

**Pull request merged**
