### PR TITLE
fixing issue-44 on linux. not sure about windows tho...

### PR DESCRIPTION
**Pull request by z00rat**
I got the idea from https://stackoverflow.com/a/52661154
it works thats kinda enough for me TBH.

Signed-off-by: zoorat <78788887+z00rat@users.noreply.github.com>

### CODE REVIEW

**Comment by JuanVqz** [comment]
you are right, this will fix the problem, I realize the same, did all the tests pass in your local env?

**Comment by z00rat** [comment]
> you are right, this will fix the problem, I realize the same, did all the tests pass in your local env?

if you mean archlinux by local env.
then yeah, its working fine my system.

**Comment by JuanVqz** [comment]
closed in favor #47

**Comment by z00rat** [comment]
np. it was fun working with you @JuanVqz

**Pull request closed without merging**
